platform :ios, '7.0'

pod 'Overcoat'
pod 'PKRevealController'
pod 'Bolts'
pod 'pop'
pod 'Tweaks'
pod 'KVOController'
pod 'MTLocation'
pod 'REMenu'
pod 'CWStatusBarNotification'
pod 'SDWebImage'
pod 'USStateAbbreviations', :git => 'https://github.com/djibouti33/US-State-Abbreviations'
pod 'DateTools'
pod 'BFNavigationBarDrawer', '~> 1.0.2'
pod 'MKToggleButton'