platform :ios, '7.0'

pod 'Overcoat'
pod 'MTLocation'
pod 'REMenu'
pod 'SDWebImage'
pod 'USStateAbbreviations', :git => 'https://github.com/djibouti33/US-State-Abbreviations'
pod 'DateTools'
pod 'pop'
pod 'CWStatusBarNotification'